name: Link Checker
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lychee:
    name: Check Markdown links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install lychee
        uses: lycheeverse/lychee-action@v2
        with:
          # Read config from repo (fallback to defaults if missing)
          args: |
            --config .lychee.toml
            --accept 200,206,429
            --max-concurrency 4
            --verbose
            **/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload lychee report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: lychee/**
